## Part 1 - Classes

1. Create a class to represent a Movie. It should have a title, a year, and a runtime (in minutes)

In [1]:
class Movie:
    """
    This class keeps track of the elements of a movie
    """
    def __init__(self, title="", year=0, runtime=0):
        self.title = title
        self.year = year

        if runtime < 0:
            runtime = 0

        self.runtime = runtime

    def __repr__(self):
        return "{} ({}) - {} mins".format(self.title, self.year, self.runtime)

    def get_runtime_hours_minutes(self):
        hours = self.runtime // 60
        minutes = self.runtime % 60

        return hours, minutes


2. Create a movie object and fill it in with appropriate data

In [2]:
m = Movie()

m.title = "Jurassic World"
m.year = 2015
m.runtime = 124

3. Override the `__repr__` method for your class to return a string version of the object in the format: "title (year) - runtime mins", such as: Jurassic World (2015) - 124 mins. Then, print out your movie using a statment like print(m)

In [3]:
print(m)

Jurassic World (2015) - 124 mins


4. Add a method to your class to return the runtime in hours and minutes (it should calculate and return both of these... yes functions can return multiple things). Verify that this method works.

In [4]:
hours, minutes = m.get_runtime_hours_minutes()
print("hours: {}, minutes: {}".format(hours, minutes))


hours: 2, minutes: 4


5. Make it so that your init function (aka constructor) can accept a title, year, and runtime if they are passed when the object is created, and set the values accordingly (but it should also allow creation of a movie with out those, using default values like "", 0, 0).

In [5]:
m2 = Movie("Beauty and the Beast", 1991, 84)
print(m2)


Beauty and the Beast (1991) - 84 mins


6. Add logic to your init function so that if the supplied runtime is less than 0, the runtime is set to 0 instead of the value supplied.

In [6]:
m3 = Movie("Test", 2000, -182)
print(m3)


Test (2000) - 0 mins


## Part 2 - Lists, List Comprehensions, Dictionaries

1. Create a function called create_movie_list() that returns a list of movies. It should create 4-5 movies, add them to a list, then return the list.



In [7]:
def create_movie_list():
    movies = []
    movies.append(Movie("Jurassic World", 2015, 124))
    movies.append(Movie("Beauty and the Beast", 1991, 84))
    movies.append(Movie("Titanic", 1997, 195))
    movies.append(Movie("test4", 2001, 400))
    movies.append(Movie("test5", 2018, 50))

    return movies

2. Call the create_movie_list() function, then iterates through each item in the list and displays it.


In [8]:
movies = create_movie_list()

print("Displaying Movies:\n")
for movie in movies:
    print(movie)

Displaying Movies:

Jurassic World (2015) - 124 mins
Beauty and the Beast (1991) - 84 mins
Titanic (1997) - 195 mins
test4 (2001) - 400 mins
test5 (2018) - 50 mins


3. Use a list comprehension to create a new list based on your original list, for all movies that have a runtime greater than 150 minutes. Loop through this list and print them out to ensure that it worked correctly.


In [9]:
long_movies = [m for m in movies if m.runtime > 150]

print("\nLong Movies:")
for movie in long_movies:
    print(movie)


Long Movies:
Titanic (1997) - 195 mins
test4 (2001) - 400 mins


4. Create a dictionary that maps movie titles to an average number of stars from the users (e.g., 4.3 stars). Add each movie title in your list to your dictionary as the key, then use a library to get a random number, and assign each movie a number of stars (0 <= stars <= 5) (including decimals).



In [10]:
import random

stars_map = {m.title : random.uniform(0, 5) for m in movies}


5. Loop through the dictionary and display the title of each movie with the number of stars it has received, showing the number of stars to 2 decimals of precision.

In [11]:
print ("\nNumber of Stars:")
for title in stars_map:
    print("{} - {:.2f} Stars".format(title, stars_map[title]))



Number of Stars:
Jurassic World - 3.82 Stars
Beauty and the Beast - 0.84 Stars
Titanic - 2.93 Stars
test4 - 0.30 Stars
test5 - 2.44 Stars


## Part 3 - NumPy

1. Assume now that we had a dataset that had three columns (all numeric): id, views, stars. Create a function that creates and returns a 2D numpy array with or random values for 10 movies and these 3 columns.

You can use the following function for this:

In [12]:
import numpy as np

def get_movie_data():
    """
    Generate a numpy array of movie data
    :return:
    """
    num_movies = 10
    array = np.zeros([num_movies, 3], dtype=np.float)

    for i in range(num_movies):
        # There is nothing magic about 100 here, just didn't want ids
        # to match the row numbers
        movie_id = i + 100

        # Lets have the views range from 100-10000
        views = random.randint(100, 10000)
        stars = random.uniform(0, 5)

        array[i][0] = movie_id
        array[i][1] = views
        array[i][2] = stars

    return array


2. Call this function and get the 2D numpy array. Then, find a way to display the number of rows in this array. On another line, display the number of columns.

In [13]:
data = get_movie_data()

print(data)


[[1.00000000e+02 7.09500000e+03 4.55619138e+00]
 [1.01000000e+02 5.41000000e+03 3.42147341e+00]
 [1.02000000e+02 5.43100000e+03 4.82719334e+00]
 [1.03000000e+02 9.28000000e+03 3.59221777e+00]
 [1.04000000e+02 3.92400000e+03 2.42734315e+00]
 [1.05000000e+02 4.95600000e+03 4.36430212e+00]
 [1.06000000e+02 5.50700000e+03 5.47862315e-02]
 [1.07000000e+02 4.88900000e+03 5.78793100e-01]
 [1.08000000e+02 3.34400000e+03 4.67717482e+00]
 [1.09000000e+02 8.78200000e+03 4.02946665e-01]]


In [14]:
rows = data.shape[0]
cols = data.shape[1]

print("There are {} rows and {} cols".format(rows, cols))



There are 10 rows and 3 cols


3. Use slicing to grab the first two rows, and display the resulting dataset.

In [15]:
print(data[0:2])


[[1.00000000e+02 7.09500000e+03 4.55619138e+00]
 [1.01000000e+02 5.41000000e+03 3.42147341e+00]]


4. Use slicing to grab the last two columns, and display the resulting dataset.

In [16]:
print(data[:,-2:])


[[7.09500000e+03 4.55619138e+00]
 [5.41000000e+03 3.42147341e+00]
 [5.43100000e+03 4.82719334e+00]
 [9.28000000e+03 3.59221777e+00]
 [3.92400000e+03 2.42734315e+00]
 [4.95600000e+03 4.36430212e+00]
 [5.50700000e+03 5.47862315e-02]
 [4.88900000e+03 5.78793100e-01]
 [3.34400000e+03 4.67717482e+00]
 [8.78200000e+03 4.02946665e-01]]


5. From your 2D array, get a 1D array of all the values in the second column (views). Make sure you get this to a 1D array, not a 2D array with one column. When you display it, it should look like: `[18, 65, 38, 12]` not like: `[[18], [65], [38], [12]]`

In [17]:
print(data[:,1])

[7095. 5410. 5431. 9280. 3924. 4956. 5507. 4889. 3344. 8782.]
